// This file is automatically generated. Do not modify it manually.
// To change this configuration, please use the Firebase console.
// https://console.firebase.google.com/project/gerador-de-sinais-158130-b1a02/settings/general/web:MTo5ODk3MTI4MjM0ODU6d2ViOmM2ZTU2Y2Q2M2E4ZTBhMzE2MDExNTA=

export const firebaseConfig = {
  "projectId": "gerador-de-sinais-158130-b1a02",
  "appId": "1:989712823485:web:c6e56cd63a8e0a31601150",
  "storageBucket": "gerador-de-sinais-158130-b1a02.appspot.com",
  "apiKey": "AIzaSyBe3e0xWd7VPAkAP_zG0ZdWk-xXv17fEaU",
  "authDomain": "gerador-de-sinais-158130-b1a02.firebaseapp.com",
  "messagingSenderId": "989712823485"
};
